steps:
### Pull cached build image
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: [ '-c', 'docker pull gcr.io/$PROJECT_ID/pandoc:latest || echo Building Docker image...']

### Build Docker image with pandoc and xeLaTeX
  - name: 'gcr.io/cloud-builders/docker'
    secretEnv: ['SSH_KEY']
    args: [
        'build',
        '--file', 'Dockerfile',
        '-t', 'gcr.io/$PROJECT_ID/pandoc:latest',
        '--cache-from', 'gcr.io/$PROJECT_ID/pandoc:latest',
        '.' ]
        

### Run pandoc using custom Docker image
  - name: 'gcr.io/$PROJECT_ID/pandoc:latest'
    entrypoint: 'bash'
    args:
    - -c
    - |
      ls -la
      pandoc --version 
      pandoc -H contrib/section_break.tex --lua-filter="./contrib/columns.lua" resume.md --pdf-engine=xelatex -o resume.pdf
      

# Setup SSH and commit generated PDF
  - name: 'gcr.io/cloud-builders/git'
    secretEnv: ['SSH_KEY']
    entrypoint: 'bash'
    args:
    - -c
    - |
      mkdir /root/.ssh
      ssh-keyscan -t rsa github.com >> /root/.ssh/known_hosts
      echo "$$SSH_KEY" >> /root/.ssh/id_rsa
      chmod 400 /root/.ssh/id_rsa
      git log -n 1
      git remote set-url --push origin git@github.com:samhiatt/my_resume
      git config --global user.email "samhiatt@gmail.com"
      git config --global user.name "Sam Hiatt"
      git status
      git add resume.pdf
      git commit -m "PDF auto-generated by pandoc from git commit $COMMIT_SHA using Google Cloud Build"
      git status
      git push -f origin master:generated


availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/gh_samhiatt_my_resume_rsa_priv/versions/latest
    env: 'SSH_KEY'


images:
  - 'gcr.io/$PROJECT_ID/pandoc:latest'

artifacts:
  objects:  
    location: 'gs://samhiatt-resume-artifacts/$COMMIT_SHA/'
    paths: ['resume.pdf']