steps:
### Pull cached build image
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: [ '-c', 'docker pull gcr.io/$PROJECT_ID/my_resume:latest']

### Build Docker image with pandoc and xeLaTeX
  - name: 'gcr.io/cloud-builders/docker'
    secretEnv: ['SSH_KEY']
    args: [
        'build',
        '--file', 'Dockerfile',
        '--build-arg','GITHUB_RSA_PRIV_KEY=$$SSH_KEY',
        '-t', 'gcr.io/$PROJECT_ID/my_resume:latest',
#        '-t', 'gcr.io/$PROJECT_ID/my_resume:$COMMIT_SHA',
        '--cache-from', 'gcr.io/$PROJECT_ID/my_resume:latest',
        '.' ]
        
#  - name: 'gcr.io/cloud-builders/#docker'
#    volumes:
#    - name: 'vol1'
#      path: '/output'
##    args: [ "run", "--rm", "-v", "vol1:/output", "gcr.io/$PROJECT_ID/output:latest"]
#    args: [ "run", "--rm", "-v", "vol1:/output", "output"]
#    args: [ 'run', '--name', #'pandoc_container', 'gcr.io/#$PROJECT_ID/my_resume:latest']
    
#  - name: 'gcr.io/cloud-builders/docker',
#    args: ['cp', 'pandoc_container:/output/resume.pdf', './resume.pdf']
 
# Access the github rsa file from Secret Manager, and setup SSH
  - name: 'gcr.io/cloud-builders/git'
    secretEnv: ['SSH_KEY']
    entrypoint: 'bash'
    args:
    - -c
    - |
      ssh-keyscan -t rsa github.com >> /root/.ssh/known_hosts
      echo "$$SSH_KEY" >> /root/.ssh/id_rsa
      chmod 400 /root/.ssh/id_rsa
      git log -n 3
      git remote -v
    volumes:
    - name: 'ssh'
      path: /root/.ssh

# TODO: run: pandoc resume.md --pdf-engine=xelatex -o /output/resume.pdf
### Run pandoc using custom Docker image
  - name: 'gcr.io/$PROJECT_ID/my_resume:latest',
    entrypoint: 'bash'
    args:
    - -c
    - |
      ls -la
      pandoc --version 
      pandoc resume.md --pdf-engine=xelatex -o resume.pdf

### Clone the repository
  #- name: 'gcr.io/cloud-builders/git'
  #  args:
  #  - clone
  #  - git@github.com:samhiatt/my_resume
  #  volumes:
  #  - name: 'ssh'
  #    path: /root/.ssh
   
### 
#  - name: 'gcr.io/cloud-builders/git'
#    entrypoint: 'bash'
#    args: ['-c', 'git status; ls -la .; ls -la /output; cd my_resume; git status']
#    volumes:
#    - name: 'ssh'
#      path: /root/.ssh
      
# Checkout $COMMIT_SHA 
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'ls -la .; git status']
    volumes:
    - name: 'ssh'
      path: /root/.ssh
    #- name: 'vol1'
    #  path: '/output' 

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/gh_samhiatt_my_resume_rsa_priv/versions/latest
    env: 'SSH_KEY'


images:
#  - 'gcr.io/$PROJECT_ID/my_resume:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/my_resume:latest'

#artifacts:
#  objects:  
#    location: 'gs://samhiatt-resume-artifacts/$COMMIT_SHA/'
#    paths: ['/output/*']