steps:
### Pull cached build image
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: [ '-c', 'docker pull gcr.io/$PROJECT_ID/pandoc:latest || echo Building Docker image...']

### Build Docker image with pandoc and xeLaTeX
  - name: 'gcr.io/cloud-builders/docker'
    secretEnv: ['SSH_KEY']
    args: [
        'build',
        '--file', 'Dockerfile',
        '-t', 'gcr.io/$PROJECT_ID/pandoc:latest',
        '--cache-from', 'gcr.io/$PROJECT_ID/pandoc:latest',
        '.' ]


# Setup git with SSH access
  - name: 'gcr.io/cloud-builders/git'
    secretEnv: ['SSH_KEY']
    entrypoint: 'bash'
    volumes: 
    - name: ssh
      path: '/root/.ssh'
    args:
    - -c
    - |
      mkdir /root/.ssh
      ssh-keyscan -t rsa github.com >> /root/.ssh/known_hosts
      echo "$$SSH_KEY" >> /root/.ssh/id_rsa
      chmod 400 /root/.ssh/id_rsa
      git log -n 3
      git remote set-url --push origin git@github.com:samhiatt/my_resume
      git config --global user.email "samhiatt@gmail.com"
      git config --global user.name "Sam Hiatt / Google Cloud Build" 
      git fetch origin generated
      git checkout -t origin/generated
      git merge master --ff-only
      git log -n 3
      if [[ ! -e generated ]]; then mkdir generated; fi
      git status


### Run pandoc using custom Docker image
  - name: 'gcr.io/$PROJECT_ID/pandoc:latest'
    entrypoint: 'bash'
    args:
    - -c
    - |
      ls -la
      pandoc --version 
      pandoc -H contrib/header.tex --lua-filter="./contrib/columns.lua" --variable "geometry=margin=1in" --variable fontsize=10pt resume.md --pdf-engine=xelatex -o generated/resume.pdf
      

# Commit generated PDF
  - name: 'gcr.io/cloud-builders/git'
    secretEnv: ['SSH_KEY']
    entrypoint: 'bash'
    volumes: 
    - name: ssh
      path: '/root/.ssh'
    args:
    - -c
    - | 
      git status
      git add generated/
      git status
      git commit -m "PDF auto-generated by pandoc from git commit $COMMIT_SHA using Google Cloud Build"
      git status
      git push origin generated


availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/gh_samhiatt_my_resume_rsa_priv/versions/latest
    env: 'SSH_KEY'


images:
  - 'gcr.io/$PROJECT_ID/pandoc:latest'

artifacts:
  objects:  
    location: 'gs://samhiatt-resume-artifacts/$COMMIT_SHA/'
    paths: ['generated/*']